version: "3"

services:
    isitup:
        image: vulnerability-examples/php-base:latest
        container_name: ssrf-isitup-lab2-10.9.0.2
        tty: true
        stdin_open: true
        volumes:
            - ./entry:/entry:ro
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.2

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
