version: "3"

services:
    ssh:
        image: vulnerability-examples/webapp-with-login
        container_name: login-localhost
        tty: true
        stdin_open: true
        volumes:
            - ./entry:/entry:ro
        ports:
            - 8080:5000
