version: "3"

services:
    ssh:
        image: frpzzd/ssh-server-docker:latest
        container_name: ssh-10.9.0.2
        tty: true
        stdin_open: true
        volumes:
            - ./run:/run
        networks:
            net-10.9.0.0:
                ipv4_address: 10.9.0.2

networks:
    net-10.9.0.0:
        name: net-10.9.0.0
        ipam:
            config:
                - subnet: 10.9.0.0/24
